databases:
  - name: trials-track-db
    plan: free
    databaseName: trialstrack
    user: trialstrackuser

services:
  - type: web
    plan: free
    name: trials-track-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn trialstrack.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trials-track-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4