# Generated by Django 4.1.3 on 2024-02-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nct_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('overall_status', models.CharField(max_length=50)),
                ('brief_summary', models.CharField(max_length=50)),
                ('detail_description', models.CharField(max_length=50)),
                ('phase', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=50)),
                ('study_first_submit_date', models.DateField()),
                ('last_update_submit_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialstrackapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalTrialLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('clinical_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialstrackapi.clinicaltrial')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialstrackapi.location')),
            ],
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='study_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialstrackapi.studytype'),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialstrackapi.user'),
        ),
    ]
