# Generated by Django 4.1.3 on 2024-02-22 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trialstrackapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaltriallocation',
            name='clinical_trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traillocations', to='trialstrackapi.clinicaltrial'),
        ),
    ]
