# Generated by Django 4.1.3 on 2024-02-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialstrackapi', '0002_patientclinicaltriallocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(),
        ),
    ]
